### ISSUE TITLE
First start

### ISSUE THREAD

**Issue by anki-code** [dyuri/xontrib-powerline-binding#1]
Hello! Thanks you for the powerline support!

I'm not the user of powerline/powerline and tried it in OMZ only but now I'm trying to test it with the xontrib but have no result. Could you help?

What I'm doing:
```bash
# bash
pip install -U git+https://github.com/xonsh/xonsh
pip install powerline-status xontrib-powerline-binding
echo 'xontrib load powerline_binding' > /tmp/xc
xonsh --rc /tmp/xc
# I see default prompt
```

Is it enough or I should do additional configuration?

After testing I'm going to add info about this xontrib to powerline repo if you agree with this.

Thanks!

**Comment by dyuri** [comment]
Thanks for taking a look!

Yep, the most difficult part is to configure powerline itself, I used my old _shell_ configuration as a starting point.

I've extended the example configuration with my colorscheme - now it contains everything what I currently use, I really hope it works now. You need to copy all the content of `example-powerline-config` under `.config/powerline` (or `$XDG_CONFIG_HOME/powerline`).

**Comment by anki-code** [comment]
> You need to copy all the content of example-powerline-config under ~/.config/powerline (or $XDG_CONFIG_HOME/powerline).

It helps. I've added some packages to make it works:
```
# bash
pip install -U git+https://github.com/xonsh/xonsh
pip install powerline-status xontrib-powerline-binding powerline-gitstatus    # added  powerline-gitstatus
pip install git+https://github.com/shimtom/powerline-exitstatus  # added

cd /tmp
git clone https://github.com/dyuri/xontrib-powerline-binding
mkdir -p ~/.config/powerline
cp xontrib-powerline-binding/example-powerline-config/* ~/.config/powerline/
echo 'xontrib load powerline_binding' > xc
xonsh --rc xc
```
And the result:
![Screenshot_20201001_220306](https://user-images.githubusercontent.com/1708680/94851999-e8c40080-0431-11eb-996c-f8c29caaaf6a.png)

Thanks!

**Comment by dyuri** [comment]
It seems your terminal marks non-breakable spaces (that's the orange underline), it can be fixed by setting `use_non_breaking_spaces` to `false`. (But it cannot be set in a local theme according to the documentation: https://powerline.readthedocs.io/en/master/configuration/reference.html)

**Comment by dyuri** [comment]
Also your right prompt is strange, this might be related to https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1241
